apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
  name: test-webhook-pvc
  namespace: test-webhook-service-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: silver